table of contents
1. Prepare
2. Data Import, Encoding
3. EDA
4. write df

# Prepare

## Import Library

In [1]:
import os, random, time

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

cmap = plt.get_cmap('tab10')

## Change matplotlib setting

In [2]:
import matplotlib as mpl

mode = 'go_ando'

if mode == 'go_ando':
    # go ando mode
    mpl.rcParams['xtick.color'] = mpl.rcParams['ytick.color'] = mpl.rcParams['axes.labelcolor'] =  'darkgrey'
    mpl.rcParams['grid.color'] = mpl.rcParams['axes.edgecolor'] = mpl.rcParams['text.color']  = 'darkgrey'
    mpl.rcParams['axes.spines.top'] = mpl.rcParams['axes.spines.right'] = False
    mpl.rcParams['axes.grid.axis'] = 'y'
    mpl.rcParams['axes.grid'] = True
    mpl.rcParams['axes.facecolor'] = mpl.rcParams['figure.facecolor'] = 'white'
elif mode == 'twitter':
    # twitter mode
    mpl.rcParams['xtick.color'] = mpl.rcParams['ytick.color'] = mpl.rcParams['axes.labelcolor'] =  'white'
    mpl.rcParams['grid.color'] = mpl.rcParams['axes.edgecolor'] = mpl.rcParams['text.color']  = 'white'
    mpl.rcParams['axes.spines.top'] = mpl.rcParams['axes.spines.right'] = False
    mpl.rcParams['axes.grid.axis'] = 'y'
    twitter_color = '#141d26'
    mpl.rcParams['axes.facecolor'] = mpl.rcParams['figure.facecolor'] = twitter_color
    
else:
    pass

## define parameter

In [3]:
base_dir = os.path.join('..','..')
data_dir = os.path.join(base_dir, 'data')
raw_dir = os.path.join(data_dir, 'raw')
processed_dir = os.path.join(data_dir, 'processed')

infile_list = os.listdir(raw_dir)
for i, infile in enumerate(infile_list):
    print(i, infile)

0 referees.json
1 teams.json
2 matches
3 competitions.json
4 events
5 players.json
6 coaches.json

# Data Import, Encoding

## Data Import

In [4]:
infile_list = os.listdir(os.path.join(raw_dir, 'matches'))
df_dict = {}
for infile in infile_list:
    df = pd.read_json(os.path.join(raw_dir, 'matches', infile))
    df_dict[infile.split('.')[0]] = df

## check data

In [5]:
for k, df in df_dict.items():
    print(k)
    display(df.head())

matches_World_Cup

,competitionId,date,dateutc,duration,gameweek,groupName,label,referees,roundId,seasonId,status,teamsData,venue,winner,wyId
0,28,2018-07-15 19:00:00,2018-07-15 15:00:00,Regular,0,,"France - Croatia, 4 - 2","[{'refereeId': 378051, 'role': 'referee'}, {'r...",4165368,10078,Played,"{'9598': {'scoreET': 0, 'coachId': 122788, 'si...",Olimpiyskiy stadion Luzhniki,4418,2058017
1,28,2018-07-14 18:00:00,2018-07-14 14:00:00,Regular,0,,"Belgium - England, 2 - 0","[{'refereeId': 380599, 'role': 'referee'}, {'r...",4165367,10078,Played,"{'2413': {'scoreET': 0, 'coachId': 276858, 'si...",Stadion Krestovskyi,5629,2058016
2,28,2018-07-11 22:00:00,2018-07-11 18:00:00,ExtraTime,0,,"Croatia - England, 2 - 1 (E)","[{'refereeId': 384995, 'role': 'referee'}, {'r...",4165366,10078,Played,"{'2413': {'scoreET': 1, 'coachId': 276858, 'si...",Olimpiyskiy stadion Luzhniki,9598,2058015
3,28,2018-07-10 22:00:00,2018-07-10 18:00:00,Regular,0,,"France - Belgium, 1 - 0","[{'refereeId': 378232, 'role': 'referee'}, {'r...",4165366,10078,Played,"{'5629': {'scoreET': 0, 'coachId': 8605, 'side...",Stadion Krestovskyi,4418,2058014
4,28,2018-07-07 22:00:00,2018-07-07 18:00:00,Penalties,0,,"Russia - Croatia, 2 - 2 (P)","[{'refereeId': 378204, 'role': 'referee'}, {'r...",4165365,10078,Played,"{'14358': {'scoreET': 2, 'coachId': 264893, 's...",Olimpiyskiy Stadion Fisht,9598,2058012

matches_Italy

,competitionId,date,dateutc,duration,gameweek,label,referees,roundId,seasonId,status,teamsData,venue,winner,wyId
0,524,"May 20, 2018 at 8:45:00 PM GMT+2",2018-05-20 18:45:00,Regular,38,"Lazio - Internazionale, 2 - 3","[{'refereeId': 377206, 'role': 'referee'}, {'r...",4406278,181248,Played,"{'3162': {'scoreET': 0, 'coachId': 251025, 'si...",,3161,2576335
1,524,"May 20, 2018 at 8:45:00 PM GMT+2",2018-05-20 18:45:00,Regular,38,"Sassuolo - Roma, 0 - 1","[{'refereeId': 377255, 'role': 'referee'}, {'r...",4406278,181248,Played,"{'3158': {'scoreET': 0, 'coachId': 210119, 'si...",MAPEI Stadium - Citt\u00e0 del Tricolore,3158,2576336
2,524,"May 20, 2018 at 6:00:00 PM GMT+2",2018-05-20 16:00:00,Regular,38,"Cagliari - Atalanta, 1 - 0","[{'refereeId': 377247, 'role': 'referee'}, {'r...",4406278,181248,Played,"{'3173': {'scoreET': 0, 'coachId': 251044, 'si...",,3173,2576329
3,524,"May 20, 2018 at 6:00:00 PM GMT+2",2018-05-20 16:00:00,Regular,38,"Chievo - Benevento, 1 - 0","[{'refereeId': 377246, 'role': 'referee'}, {'r...",4406278,181248,Played,"{'3165': {'scoreET': 0, 'coachId': 272970, 'si...",,3165,2576330
4,524,"May 20, 2018 at 6:00:00 PM GMT+2",2018-05-20 16:00:00,Regular,38,"Udinese - Bologna, 1 - 0","[{'refereeId': 377254, 'role': 'referee'}, {'r...",4406278,181248,Played,"{'3166': {'scoreET': 0, 'coachId': 20481, 'sid...",,3163,2576331

matches_Germany

,competitionId,date,dateutc,duration,gameweek,label,referees,roundId,seasonId,status,teamsData,venue,winner,wyId
0,426,"May 12, 2018 at 3:30:00 PM GMT+2",2018-05-12 13:30:00,Regular,34,"Bayern M\u00fcnchen - Stuttgart, 1 - 4","[{'refereeId': 379444, 'role': 'referee'}, {'r...",4405517,181137,Played,"{'2444': {'scoreET': 0, 'coachId': 14710, 'sid...",Allianz Arena,2445,2517036
1,426,"May 12, 2018 at 3:30:00 PM GMT+2",2018-05-12 13:30:00,Regular,34,"Hoffenheim - Borussia Dortmund, 3 - 1","[{'refereeId': 384936, 'role': 'referee'}, {'r...",4405517,181137,Played,"{'2482': {'scoreET': 0, 'coachId': 272299, 'si...",WIRSOL Rhein-Neckar-Arena,2482,2517037
2,426,"May 12, 2018 at 3:30:00 PM GMT+2",2018-05-12 13:30:00,Regular,34,"Hertha BSC - RB Leipzig, 2 - 6","[{'refereeId': 387276, 'role': 'referee'}, {'r...",4405517,181137,Played,"{'2457': {'scoreET': 0, 'coachId': 18987, 'sid...",Olympiastadion Berlin,2975,2517038
3,426,"May 12, 2018 at 3:30:00 PM GMT+2",2018-05-12 13:30:00,Regular,34,"Freiburg - Augsburg, 2 - 0","[{'refereeId': 378957, 'role': 'referee'}, {'r...",4405517,181137,Played,"{'2453': {'scoreET': 0, 'coachId': 14977, 'sid...",Schwarzwald-Stadion,2453,2517039
4,426,"May 12, 2018 at 3:30:00 PM GMT+2",2018-05-12 13:30:00,Regular,34,"Schalke 04 - Eintracht Frankfurt, 1 - 0","[{'refereeId': 387273, 'role': 'referee'}, {'r...",4405517,181137,Played,"{'2449': {'scoreET': 0, 'coachId': 447924, 'si...",VELTINS-Arena,2449,2517040

matches_England

,competitionId,date,dateutc,duration,gameweek,label,referees,roundId,seasonId,status,teamsData,venue,winner,wyId
0,364,"May 13, 2018 at 4:00:00 PM GMT+2",2018-05-13 14:00:00,Regular,38,"Burnley - AFC Bournemouth, 1 - 2","[{'refereeId': 385705, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1646': {'scoreET': 0, 'coachId': 8880, 'side...",Turf Moor,1659,2500089
1,364,"May 13, 2018 at 4:00:00 PM GMT+2",2018-05-13 14:00:00,Regular,38,"Crystal Palace - West Bromwich Albion, 2 - 0","[{'refereeId': 381851, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1628': {'scoreET': 0, 'coachId': 8357, 'side...",Selhurst Park,1628,2500090
2,364,"May 13, 2018 at 4:00:00 PM GMT+2",2018-05-13 14:00:00,Regular,38,"Huddersfield Town - Arsenal, 0 - 1","[{'refereeId': 384965, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1609': {'scoreET': 0, 'coachId': 7845, 'side...",The John Smith's Stadium,1609,2500091
3,364,"May 13, 2018 at 4:00:00 PM GMT+2",2018-05-13 14:00:00,Regular,38,"Liverpool - Brighton & Hove Albion, 4 - 0","[{'refereeId': 385704, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1651': {'scoreET': 0, 'coachId': 8093, 'side...",Anfield,1612,2500092
4,364,"May 13, 2018 at 4:00:00 PM GMT+2",2018-05-13 14:00:00,Regular,38,"Manchester United - Watford, 1 - 0","[{'refereeId': 381853, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1644': {'scoreET': 0, 'coachId': 93112, 'sid...",Old Trafford,1611,2500093

matches_France

,competitionId,date,dateutc,duration,gameweek,label,referees,roundId,seasonId,status,teamsData,venue,winner,wyId
0,412,"May 19, 2018 at 9:00:00 PM GMT+2",2018-05-19 19:00:00,Regular,38,"Caen - PSG, 0 - 0","[{'refereeId': 384954, 'role': 'referee'}, {'r...",4405655,181189,Played,"{'3783': {'scoreET': 0, 'coachId': 210513, 'si...",Stade Michel d'Ornano,0,2501056
1,412,"May 19, 2018 at 9:00:00 PM GMT+2",2018-05-19 19:00:00,Regular,38,"Dijon - Angers SCO, 2 - 1","[{'refereeId': 385496, 'role': 'referee'}, {'r...",4405655,181189,Played,"{'3804': {'scoreET': 0, 'coachId': 220743, 'si...",Stade Gaston-G\u00e9rard,0,2501057
2,412,"May 19, 2018 at 9:00:00 PM GMT+2",2018-05-19 19:00:00,Regular,38,"Olympique Lyonnais - Nice, 3 - 2","[{'refereeId': 386297, 'role': 'referee'}, {'r...",4405655,181189,Played,"{'3766': {'scoreET': 0, 'coachId': 211238, 'si...",Groupama Stadium,3766,2501058
3,412,"May 19, 2018 at 9:00:00 PM GMT+2",2018-05-19 19:00:00,Regular,38,"Olympique Marseille - Amiens SC, 2 - 1","[{'refereeId': 385529, 'role': 'referee'}, {'r...",4405655,181189,Played,"{'3771': {'scoreET': 0, 'coachId': 25691, 'sid...",Stade V\u00e9lodrome,3771,2501059
4,412,"May 19, 2018 at 9:00:00 PM GMT+2",2018-05-19 19:00:00,Regular,38,"Metz - Bordeaux, 0 - 4","[{'refereeId': 385796, 'role': 'referee'}, {'r...",4405655,181189,Played,"{'3772': {'scoreET': 0, 'coachId': 9092, 'side...",Stade Saint-Symphorien,3772,2501060

matches_Spain

,competitionId,date,dateutc,duration,gameweek,label,referees,roundId,seasonId,status,teamsData,venue,winner,wyId
0,795,"May 20, 2018 at 8:45:00 PM GMT+2",2018-05-20 18:45:00,Regular,38,"Barcelona - Real Sociedad, 1 - 0","[{'refereeId': 398931, 'role': 'referee'}, {'r...",4406122,181144,Played,"{'676': {'scoreET': 0, 'coachId': 92894, 'side...",Camp Nou,676,2565922
1,795,"May 20, 2018 at 6:30:00 PM GMT+2",2018-05-20 16:30:00,Regular,38,"Atl\u00e9tico Madrid - Eibar, 2 - 2","[{'refereeId': 395056, 'role': 'referee'}, {'r...",4406122,181144,Played,"{'679': {'scoreET': 0, 'coachId': 3427, 'side'...",Estadio Wanda Metropolitano,0,2565925
2,795,"May 20, 2018 at 4:15:00 PM GMT+2",2018-05-20 14:15:00,Regular,38,"Athletic Club - Espanyol, 0 - 1","[{'refereeId': 384957, 'role': 'referee'}, {'r...",4406122,181144,Played,"{'691': {'scoreET': 0, 'coachId': 444778, 'sid...",San Mam\u00e9s Barria,691,2565919
3,795,"May 20, 2018 at 12:00:00 PM GMT+2",2018-05-20 10:00:00,Regular,38,"Valencia - Deportivo La Coru\u00f1a, 2 - 1","[{'refereeId': 398913, 'role': 'referee'}, {'r...",4406122,181144,Played,"{'674': {'scoreET': 0, 'coachId': 210074, 'sid...",Estadio de Mestalla,674,2565924
4,795,"May 19, 2018 at 8:45:00 PM GMT+2",2018-05-19 18:45:00,Regular,38,"Villarreal - Real Madrid, 2 - 2","[{'refereeId': 395085, 'role': 'referee'}, {'r...",4406122,181144,Played,"{'675': {'scoreET': 0, 'coachId': 275283, 'sid...",Estadio de la Cer\u00e1mica,0,2565927

matches_European_Championship

,competitionId,date,dateutc,duration,gameweek,groupName,label,referees,roundId,seasonId,status,teamsData,venue,winner,wyId
0,102,2016-07-10 23:00:00,2016-07-10 19:00:00,ExtraTime,0,Group F,"Portugal - France, 1 - 0 (E)","[{'refereeId': 381617, 'role': 'referee'}, {'r...",4165474,9291,Played,"{'9905': {'scoreET': 1, 'coachId': 137521, 'si...",Stade de France,9905,1694440
1,102,2016-07-07 23:00:00,2016-07-07 19:00:00,Regular,0,Group F,"Germany - France, 0 - 2","[{'refereeId': 377209, 'role': 'referee'}, {'r...",4165473,9291,Played,"{'3148': {'scoreET': 0, 'coachId': 134365, 'si...",Stade V\u00e9lodrome,4418,1694439
2,102,2016-07-06 23:00:00,2016-07-06 19:00:00,Regular,0,Group F,"Portugal - Wales, 2 - 0","[{'refereeId': 384373, 'role': 'referee'}, {'r...",4165473,9291,Played,"{'10682': {'scoreET': 0, 'coachId': 136439, 's...",Groupama Stadium,9905,1694438
3,102,2016-07-03 23:00:00,2016-07-03 19:00:00,Regular,0,Group F,"France - Iceland, 5 - 2","[{'refereeId': 377215, 'role': 'referee'}, {'r...",4165472,9291,Played,"{'7839': {'scoreET': 0, 'coachId': 210205, 'si...",Stade de France,4418,1694437
4,102,2016-07-02 23:00:00,2016-07-02 19:00:00,Penalties,0,Group F,"Germany - Italy, 1 - 1 (P)","[{'refereeId': 383185, 'role': 'referee'}, {'r...",4165472,9291,Played,"{'3148': {'scoreET': 1, 'coachId': 134365, 'si...",Stade Matmut-Atlantique,3148,1694436

# EDA

In [6]:
for k, df in df_dict.items():
    print(f'{k}')
    print(f'\t- Number of matches = {len(df.wyId.unique())}')
    print(f'\t- Number of rows = {len(df)}')

matches_World_Cup
	- Number of matches = 64
	- Number of rows = 64
matches_Italy
	- Number of matches = 380
	- Number of rows = 380
matches_Germany
	- Number of matches = 306
	- Number of rows = 306
matches_England
	- Number of matches = 380
	- Number of rows = 380
matches_France
	- Number of matches = 380
	- Number of rows = 380
matches_Spain
	- Number of matches = 380
	- Number of rows = 380
matches_European_Championship
	- Number of matches = 51
	- Number of rows = 51

In [9]:
for k, df in df_dict.items():
    print(f'{k}')
    df.dateutc = pd.to_datetime(df.dateutc, utc=True)
    summary = df.groupby(df.dateutc.dt.year).size().to_frame()
    display(summary)

matches_World_Cup

          0
dateutc
2018     64

matches_Italy

           0
dateutc
2017     188
2018     192

matches_Germany

           0
dateutc
2017     153
2018     153

matches_England

           0
dateutc
2017     209
2018     171

matches_France

           0
dateutc
2017     190
2018     190

matches_Spain

           0
dateutc
2017     169
2018     211

matches_European_Championship

          0
dateutc
2016     51

# write df

In [7]:
for k, df in df_dict.items():
    df.to_csv(os.path.join(processed_dir, 'matches', f'{k}.csv'), index=False)